export interface Product {
  id?: string;
  amount: number;
  name: string;
  company: string;
  ean: string;
  barcode: string;
  price: number;
  retailPrice: number | null;
  unitPrice: number | null;
  images: string[];
  category: string;
  energyJoule: number | null;
  energyCalory: number | null;
  fat: number | null;
  saturatedFat: number | null;
  carbohydrate: number | null;
  saturatedCarbohydrate: number | null;
  protein: number | null;
  salt: number | null;
  fiber: number | null;
  countryOfOrigin?: string;
  ingredients_fi?: string;
  ingredients_sv?: string;
  ingredients_en?: string;
  description_fi?: string;
  description_sv?: string;
  description_en?: string;
  showInWebshop: boolean;
}
